export const STUDENT_REGISTER_START = "STUDENT_REGISTER_START";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";

export const STUDENT_SIGNING_START = "STUDENT_SIGNING_START";
export const STUDENT_SIGNING_SUCCESS = "STUDENT_SIGNING_SUCCESS";
export const STUDENT_SIGNING_FAIL = "STUDENT_SIGNING_FAIL";

export const TUTOR_REGISTER_START = "TUTOR_REGISTER_START";
export const TUTOR_REGISTER_SUCCESS = "TUTOR_REGISTER_SUCCESS";
export const TUTOR_REGISTER_FAIL = "TUTOR_REGISTER_FAIL";

export const TUTOR_SIGNING_START = "TUTOR_SIGNING_START";
export const TUTOR_SIGNING_SUCCESS = "TUTOR_SIGNING_SUCCESS";
export const TUTOR_SIGNING_FAIL = "TUTOR_SIGNING_FAIL";

export const STUDENT_LOGOUT_START = "STUDENT_LOGOUT_START";
export const STUDENT_LOGOUT_SUCCESS = "STUDENT_LOGOUT_SUCCESS";
export const STUDENT_LOGOUT_FAIL = "STUDENT_LOGOUT_FAIL";

export const TUTOR_LOGOUT_START = "TUTOR_LOGOUT_START";
export const TUTOR_LOGOUT_SUCCESS = "TUTOR_LOGOUT_SUCCESS";
export const TUTOR_LOGOUT_FAIL = "TUTOR_LOGOUT_FAIL";
